### ISSUE TITLE
Import module (ES6)

### ISSUE THREAD

**Issue by josephmiclaus** [mmw/react-password-strength#28]
Is there any good way to import the module ?

Something like this would be nice:

`import ReactPasswordStrength from 'react-password-strength'`

Thanks !

**Comment by mmw** [comment]
Yep, that syntax should work fine (I'm using the same in production). Let me know if you have any issues.

**Comment by mmw** [comment]
Closing as this seems resolved, feel free to reopen if you experience some issues importing the module

**Comment by josephmiclaus** [comment]
Jup it works, sorry for the **false alarm**. 

Flow didn't fully scan all modules.

Thanks :)
