### ISSUE TITLE
window is not defined for SSR

### ISSUE THREAD

**Issue by scarletfog** [mmw/react-password-strength#29]
window is not defined for SSR
```
node_modules/react-password-strength/dist/index.js:339
return /msie [6-9]\b/.test(window.navigator.userAgent.toLowerCase());
```

**Comment by mmw** [comment]
Will look into this but this week I'm very busy with client work. Feel free to submit a PR if you have a fix in mind.

**Comment by mmw** [comment]
@scarletfog I've got a PR for this issue. Can you try to use in your project so I can confirm the fix?

Steps to test:
- `npm uninstall --save-dev react-password-strength` (if you currently have it installed in your project)
- `npm install --save-dev git://github.com/mmw/react-password-strength.git#fix-iso-issue`
- `cd ./node_modules/react-password-strenth && npm run prepublish`
-  In your source code change the import path to `import ReactPasswordStrength from 'react-password-strength/dist/universal';`
- You will need to require/import `react-password-strength/dist/style.css` somewhere (this depends on how you setup your SSR app)
