### ISSUE TITLE
Focus on mount

### ISSUE THREAD

**Issue by aymericbouzy** [mmw/react-password-strength#32]
I would like the component to focus on mount. How can I do that ?
If it's not possible with the current component, I can create a PR to add this feature.

**Comment by mmw** [comment]
use `inputProps` to pass props to the input field.

Something like the following should work:

```
<ReactPasswordStrength
  inputProps={{ autofocus: true }}
/>
```

**Comment by mmw** [comment]
I do this in the example: https://github.com/mmw/react-password-strength/blob/master/example/index.js#L26
