### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by binarykitchen** [mmw/react-password-strength#33]
Time to bump to React v15.5.x?

**Comment by mmw** [comment]
Not quite the fix, we need to use `prop-types` npm package instead of pulling `propTypes` from `react`. Feel free to submit a PR if you are up for the fix otherwise I'll look into it when I have time. This doesnt break anything, just a warning of deprecation.
