### ISSUE TITLE
Add new inputProp.defaultClassName to amend class names instead of overwriting

### ISSUE THREAD

**Issue by binarykitchen** [mmw/react-password-strength#38]
Currently `inputProps.className` overwrites all and basically, it makes internal CSS classes for displaying validity obsolete.

In my case I only want to amend another class name without overwriting any internal CSS classes. Something like `inputProps.defaultClassName` which I could set to i.E. `form-control` so that bootstrap styles can be added to.

**Comment by mmw** [comment]
Feel free to submit a PR, otherwise when I have time I'll add this feature

**Comment by binarykitchen** [comment]
here you go @mmw
