### ISSUE TITLE
Do not display score word OK when min length is not met

### ISSUE THREAD

**Issue by binarykitchen** [mmw/react-password-strength#39]
When you have set a min length of i.E. 8 and enter a shorter password which DOES meet the min score, the input score word is `OK` which is irritating.

Should display `too short` or something like that.

**Comment by mmw** [comment]
This should be an option/toggle. Having the word `OK` for the lowest password strength score feels incorrect fwiw. Feel free to submit a PR, otherwise I'll get to it when I have some free time

**Comment by binarykitchen** [comment]
here you go @mmw
