### ISSUE TITLE
Support for material-ui

### ISSUE THREAD

**Issue by sahilchopra** [mmw/react-password-strength#52]

**Comment by mmw** [comment]
care to provide some detail on what exactly you want and why?

**Comment by sahilchopra** [comment]
Hi I am using material-ui in my project. 
I was wondering, any way to support material-ui in this library 

http://www.material-ui.com/#/customization/themes

**Comment by mmw** [comment]
Not really, there was a similar issue raised a little while ago to support 3rd party render options. I think your best bet is to look at the source and just implement in your project from scratch, this isnt a very complex tool

Good luck with your project!
