### ISSUE TITLE
Unable to set value - for multi step form

### ISSUE THREAD

**Issue by sanjitbauliibm** [mmw/react-password-strength#55]
having trouble when i am using two-step form. when back from step 2 password become empty again

**Comment by mmw** [comment]
Is your project public? Can you share your code? I'm not sure this is a problem with the password field exactly..

**Comment by mmw** [comment]
Oh, I think I got it. Your issue is that you cant pre-populate the password field with a password? I can see that being an issue. Will look into fixing it

**Comment by sanjitbauliibm** [comment]
Thank you get it right. also, i hope this will calculate the strength and also show messages and bar accordingly.
will be waiting for the fix.

**Comment by mmw** [comment]
ok Ill try to find some time to look into it but I cant promise a speedy update. Feel free to submit a pr in the meantime

**Comment by denispasin** [comment]
Changing the constructor by:
```js
  constructor(props) {
    super(props);

    this.state = {
      score: 0,
      isValid: false,
      password: props.inputProps.value || '',
    };
  }
```
Did the trick for me.

**Comment by jh9027** [comment]
I've created a PR for this: https://github.com/mmw/react-password-strength/pull/56/files

My use case is the same as @sanjitbauliibm (multi-step form) and I have an example working locally with the new 'defaultValue' prop.

**Comment by zaratan** [comment]
I feel like it's not the same 'issue'. I see it more as a managed field (like the value is stored in redux as the single source of truth) vs self contained field. But the "default" value is a good idea.

**Comment by mmw** [comment]
@denispasin can you elaborate? from what @sanjitbauliibm said I understand it to the be the fix he was looking for. Closing this issue now but we can discuss further any feature changes needed
