### ISSUE TITLE
Unresolved module in build

### ISSUE THREAD

**Issue by salpulse** [mmw/react-password-strength#61]
The package is working, but when I build (with Meteor) I get:

```Unable to resolve some modules:

  "!!../node_modules/css-loader/index.js!./style.css" in /Users/xxx/Working/yyy/node_modules/react-password-strength/dist/index.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save !!..
 ```

This error stops me deploying to production. I have run `npm install --save` but this does not update anything.

**Comment by mmw** [comment]
Have you researched this issue yourself? On google I find lots of related issues with other packages in meteor. As of right now I find it unconvincing this is an issue with react-password-strength and more likely an issue in your setup/meteor.

I dont personally use meteor so Im not sure how to help. If you have evidence this is an issue with react-pass-strength post here and Ill investigate.
