### ISSUE TITLE
onChange not working

### ISSUE THREAD

**Issue by ShubhamKushwah** [mmw/react-password-strength#64]
If passed as props `onChange` won't work for the input inside the component, because it would trigger the function in the current component.
```
inputProps={{ onChange: this.handleChange }}
```
Currently, we can only send the props as a string.

**Comment by mmw** [comment]
`onChange` is a protected prop, see [docs](https://github.com/mmw/react-password-strength#inputprops) please use [changeCallback](https://github.com/mmw/react-password-strength#changecallback) instead it should be enough for 99% of use cases. If you have an edge case please let me know and I'll see what the options are
