### ISSUE TITLE
Placeholder not being displayed

### ISSUE THREAD

**Issue by anking** [mmw/react-password-strength#65]
Adding placeholder attribute is not refleted in final component render, seem like it gets omitted. Is there a way to get this fixed?

**Comment by mmw** [comment]
Works fine in the [example](https://reactpasswordstrength.netlify.com/) are you sure you are passing the placeholder correctly? See render method of [example code](https://github.com/mmw/react-password-strength-example/blob/master/src/App.js#L12)
