### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by asawyers** [mmw/react-password-strength#70]
Hey, I attempted to use this package and got stuck at the import statement from the README:

```
Unable to resolve module `!!../node_modules/css-loader/index.js!./style.css` from `/Users/asawyers/Documents/Zenblock/React/react-native-zenblock/node_modules/react-password-strength/dist/index.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.

ABI25_0_0RCTFatal
__37-[ABI25_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

I saw the other issue in here, but I am not using meteor. This also throws a different error. I tried all the suggestions in the error as well.

Google searches come up with meteor only solutions.

Any ideas?

**Comment by dangerbell** [comment]
I also got this problem. It seems like the default import has a bunch of webpack-specific stuff for loading both js and css from the same import. I used the "universal" import they mention in the readme and it loaded ok.

**Comment by mmw** [comment]
I think Greg has the correct answer. In the default module we import CSS, if importing the universal build doesn't work for you please update here. Closing for now.
